# Generated by Django 2.2.6 on 2020-07-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_auto_20200705_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category_id',
            new_name='category',
        ),
    ]
